name: test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Cache nx directory
      uses: actions/cache@master
      with:
        path: |
          .nx
        key: ${{ runner.os }}-nx-${{ hashFiles('**/nx/**') }}
        restore-keys: |
          ${{ runner.os }}-nx-

    - name: Display structure of cached files
      run: ls -R

    - name: Install dependencies
      run: npm install

    - name: Run 
      run: | 
        npm start