name: test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Restore Cached nx directory
      uses: actions/cache/restore@v3
      with:
        path: |
          .nx
        key: ${{ runner.os }}-nx-${{ hashFiles('**/nx/**') }}
        restore-keys: |
          ${{ runner.os }}-nx-

    - name: Install dependencies
      run: npm install

    - name: Display structure of cached files
      run: ls -R

    - name: Run 
      run: | 
        npm start

    - name: Clear Cache
      run: npx actions/invalidate-cache --path .nx
    
    - name: Caching nx directory
      uses: actions/cache/save@v3
      with:
          path: |
            .nx
          key: ${{ runner.os }}-nx-